export const manifest = [
	`Do you remember the days when you could simply plug in a device and it would WORK? `,
	`No fuss, no muss! ~Just pure, unadulterated FUNCTIONALITY! `,
	'',
	`Your television had only three channels, but each one was a treasure trove of entertainment.`,
	`You didn't have to scroll through endless options, just good old-fashioned FAMILY TIME! `,
	`And what about the days when your car didn't require a PhD in engineering to operate? `,
	// `You could simply turn the key and GO! No check engine lights, no complicated dashboards, just the open road and the wind in your hair!`,
	'',
	`Do you remember the days when your phone was just a PHONE? `,
	`You could pick it up, dial a number.`, //, and have a conversation without worrying about dropped calls or dead batteries! ,
	`It was as simple as that! `,
	'',
	`Can you recall the sweet sound of a dial-up modem connecting to the internet? `,
	`The thrill of hearing that familiar tone, knowing that you were about to embark on a digital adventure?`,
	'',
	`And what about your computer?`,
	`Remember when it was just a tool to help you get your work done? No endless updates, no confusing interfaces, just a reliable machine that did what you needed it to do! `,
	`It was like having a trusty steed that never let you down!`,
	// '',
	// `Do you remember the days when you could walk into a store and buy a product without having to read a 10-page manual? `,
	// `You could just pick it up, plug it in, and BAM! It worked! No troubleshooting, no headaches, just pure bliss!`,
	'',
	`LNOX is a software company. `,
	`And we believe in bringing back those days of simplicity and reliability! `,
	`We are dedicated to creating software that just~ WORKS!~ `,
	`No more confusion, no more frustration, just pure FUNCTIONALITY! `,
	`Let us help you rediscover the joy of technology that works for YOU!`,
	`LNOX is a software company, this is what we do best!`
];
